//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoRealEstate.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContosoRealEstate.BusinessLogic.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter {0} of value &apos;{1}&apos;.
        /// </summary>
        internal static string INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin registration..
        /// </summary>
        internal static string INVALID_PLUGIN_MESSAGE_REGISTRATION {
            get {
                return ResourceManager.GetString("INVALID_PLUGIN_MESSAGE_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listing cannot be changed on an existing reservation..
        /// </summary>
        internal static string LISTING_CANNOT_BE_CHANGED {
            get {
                return ResourceManager.GetString("LISTING_CANNOT_BE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listing is not available for these dates..
        /// </summary>
        internal static string LISTING_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("LISTING_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required input parameters..
        /// </summary>
        internal static string MISSING_INPUT_PARAMETERS {
            get {
                return ResourceManager.GetString("MISSING_INPUT_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected image &apos;PreImage&apos; is missing..
        /// </summary>
        internal static string PREIMAGE_MISSING {
            get {
                return ResourceManager.GetString("PREIMAGE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation cannot be null..
        /// </summary>
        internal static string RESERVATION_NULL {
            get {
                return ResourceManager.GetString("RESERVATION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be after the From date..
        /// </summary>
        internal static string TO_DATE_MUST_BE_AFTER_FROM_DATE {
            get {
                return ResourceManager.GetString("TO_DATE_MUST_BE_AFTER_FROM_DATE", resourceCulture);
            }
        }
    }
}
