#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoRealEstate.BusinessLogic.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("contoso_ReserveListingApi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class contoso_ReserveListingApiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string To
		{
			get
			{
				if (this.Parameters.Contains("To"))
				{
					return ((string)(this.Parameters["To"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["To"] = value;
			}
		}
		
		public string ListingID
		{
			get
			{
				if (this.Parameters.Contains("ListingID"))
				{
					return ((string)(this.Parameters["ListingID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ListingID"] = value;
			}
		}
		
		public string DataverseUserId
		{
			get
			{
				if (this.Parameters.Contains("DataverseUserId"))
				{
					return ((string)(this.Parameters["DataverseUserId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DataverseUserId"] = value;
			}
		}
		
		public string From
		{
			get
			{
				if (this.Parameters.Contains("From"))
				{
					return ((string)(this.Parameters["From"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["From"] = value;
			}
		}
		
		public int Guests
		{
			get
			{
				if (this.Parameters.Contains("Guests"))
				{
					return ((int)(this.Parameters["Guests"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Guests"] = value;
			}
		}
		
		public contoso_ReserveListingApiRequest()
		{
			this.RequestName = "contoso_ReserveListingApi";
			this.To = default(string);
			this.ListingID = default(string);
			this.DataverseUserId = default(string);
			this.From = default(string);
			this.Guests = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("contoso_ReserveListingApi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class contoso_ReserveListingApiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public contoso_ReserveListingApiResponse()
		{
		}
		
		public string ReservationNumber
		{
			get
			{
				if (this.Results.Contains("ReservationNumber"))
				{
					return ((string)(this.Results["ReservationNumber"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
