#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoRealEstate.BusinessLogic.Models
{
	
	
	/// <summary>
	/// Status of the Listing Reservation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum contoso_reservation_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Listing Reservation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum contoso_reservation_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("contoso_reservation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class contoso_Reservation : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the contoso_reservation entity
		/// </summary>
		public partial class Fields
		{
			public const string contoso_Amount = "contoso_amount";
			public const string contoso_amount_Base = "contoso_amount_base";
			public const string contoso_CheckoutExpiry = "contoso_checkoutexpiry";
			public const string contoso_CheckoutSessionUrl = "contoso_checkoutsessionurl";
			public const string contoso_Customer = "contoso_customer";
			public const string contoso_From = "contoso_from";
			public const string contoso_Guests = "contoso_guests";
			public const string contoso_Listing = "contoso_listing";
			public const string contoso_Name = "contoso_name";
			public const string contoso_Nights = "contoso_nights";
			public const string contoso_ReservationDate = "contoso_reservationdate";
			public const string contoso_ReservationId = "contoso_reservationid";
			public const string Id = "contoso_reservationid";
			public const string contoso_ReservationNumber = "contoso_reservationnumber";
			public const string contoso_ReservationStatus = "contoso_reservationstatus";
			public const string contoso_SessionID = "contoso_sessionid";
			public const string contoso_To = "contoso_to";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string contoso_reservation_Customer_contact = "contoso_reservation_Customer_contact";
			public const string contoso_reservation_listing = "contoso_reservation_listing";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public contoso_Reservation() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "contoso_reservation";
		
		public const string EntityLogicalCollectionName = "contoso_reservations";
		
		public const string EntitySetName = "contoso_reservations";
		
		/// <summary>
		/// Reservation Amount Charged
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_amount")]
		public Microsoft.Xrm.Sdk.Money contoso_Amount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("contoso_amount");
			}
			set
			{
				this.SetAttributeValue("contoso_amount", value);
			}
		}
		
		/// <summary>
		/// Value of the Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_amount_base")]
		public Microsoft.Xrm.Sdk.Money contoso_amount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("contoso_amount_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_checkoutexpiry")]
		public System.Nullable<System.DateTime> contoso_CheckoutExpiry
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("contoso_checkoutexpiry");
			}
			set
			{
				this.SetAttributeValue("contoso_checkoutexpiry", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_checkoutsessionurl")]
		public string contoso_CheckoutSessionUrl
		{
			get
			{
				return this.GetAttributeValue<string>("contoso_checkoutsessionurl");
			}
			set
			{
				this.SetAttributeValue("contoso_checkoutsessionurl", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_customer")]
		public Microsoft.Xrm.Sdk.EntityReference contoso_Customer
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contoso_customer");
			}
			set
			{
				this.SetAttributeValue("contoso_customer", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_from")]
		public System.Nullable<System.DateTime> contoso_From
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("contoso_from");
			}
			set
			{
				this.SetAttributeValue("contoso_from", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_guests")]
		public System.Nullable<int> contoso_Guests
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("contoso_guests");
			}
			set
			{
				this.SetAttributeValue("contoso_guests", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_listing")]
		public Microsoft.Xrm.Sdk.EntityReference contoso_Listing
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contoso_listing");
			}
			set
			{
				this.SetAttributeValue("contoso_listing", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_name")]
		public string contoso_Name
		{
			get
			{
				return this.GetAttributeValue<string>("contoso_name");
			}
			set
			{
				this.SetAttributeValue("contoso_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_nights")]
		public System.Nullable<int> contoso_Nights
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("contoso_nights");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_reservationdate")]
		public System.Nullable<System.DateTime> contoso_ReservationDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("contoso_reservationdate");
			}
			set
			{
				this.SetAttributeValue("contoso_reservationdate", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_reservationid")]
		public System.Nullable<System.Guid> contoso_ReservationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("contoso_reservationid");
			}
			set
			{
				this.SetAttributeValue("contoso_reservationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_reservationid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.contoso_ReservationId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_reservationnumber")]
		public string contoso_ReservationNumber
		{
			get
			{
				return this.GetAttributeValue<string>("contoso_reservationnumber");
			}
			set
			{
				this.SetAttributeValue("contoso_reservationnumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_reservationstatus")]
		public virtual contoso_reservationstatus? contoso_ReservationStatus
		{
			get
			{
				return ((contoso_reservationstatus?)(EntityOptionSetEnum.GetEnum(this, "contoso_reservationstatus")));
			}
			set
			{
				this.SetAttributeValue("contoso_reservationstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Temporary identifier for Power Fx Plugins because you can't use Patch
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_sessionid")]
		public string contoso_SessionID
		{
			get
			{
				return this.GetAttributeValue<string>("contoso_sessionid");
			}
			set
			{
				this.SetAttributeValue("contoso_sessionid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_to")]
		public System.Nullable<System.DateTime> contoso_To
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("contoso_to");
			}
			set
			{
				this.SetAttributeValue("contoso_to", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Reservation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual contoso_reservation_statecode? statecode
		{
			get
			{
				return ((contoso_reservation_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Reservation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual contoso_reservation_statuscode? statuscode
		{
			get
			{
				return ((contoso_reservation_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 contoso_reservation_Customer_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_customer")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contoso_reservation_Customer_contact")]
		public ContosoRealEstate.BusinessLogic.Models.Contact contoso_reservation_Customer_contact
		{
			get
			{
				return this.GetRelatedEntity<ContosoRealEstate.BusinessLogic.Models.Contact>("contoso_reservation_Customer_contact", null);
			}
			set
			{
				this.SetRelatedEntity<ContosoRealEstate.BusinessLogic.Models.Contact>("contoso_reservation_Customer_contact", null, value);
			}
		}
		
		/// <summary>
		/// N:1 contoso_reservation_listing
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contoso_listing")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contoso_reservation_listing")]
		public ContosoRealEstate.BusinessLogic.Models.contoso_listing contoso_reservation_listing
		{
			get
			{
				return this.GetRelatedEntity<ContosoRealEstate.BusinessLogic.Models.contoso_listing>("contoso_reservation_listing", null);
			}
			set
			{
				this.SetRelatedEntity<ContosoRealEstate.BusinessLogic.Models.contoso_listing>("contoso_reservation_listing", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
